# Generated by Django 5.1.1 on 2024-09-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
