# Generated by Django 5.1.1 on 2024-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
